# Generated by Django 5.1.2 on 2024-10-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(null=True)),
                ('status', models.CharField(default='To Do', max_length=500, null=True)),
            ],
        ),
    ]
